datasource:
  password: 12345
  username: root
  hostname: jdbc:mysql://localhost:3306/depth_stream
  driverClassName: com.mysql.cj.jdbc.Driver
  entityPackage: com.example.diffbookdepthstreams.entity


binance:
  socketUrl: wss://dstream.binance.com/stream?streams=btcusd_perp@depth@%sms
  depthUrl: https://dapi.binance.com/dapi/v1/depth?symbol=btcusd_perp&limit=1000
